Language Update #1
OpenProfileDevs/OP5-Preview pull request #1
Opened 2023-09-18 04:47 UTC by im-a-dweeb

I've gone ahead and added 2 more languages along with 1 special one ;) (Ava, please don't kill me I have a family-)

- Suisse French
- Deutsch
- Special One ;)

2023-09-18 05:21 UTC, AvatarKage requested changes
I've commented on a few things that need to be addressed before this merge can be completed!

2023-09-18 05:21 UTC, AvatarKage commented on translations/pirate-us.json
> +}
This isn't something we're looking for!

2023-09-18 05:21 UTC, AvatarKage commented on index.html
> +          <li id="pirate">🏴‍☠️Pirate</li>
Find emotes that represents the native language appropriately or at least the country of origin. Flags don't show on all devices! Also remove the pirate as it's not what we're looking for.

2023-09-18 05:21 UTC, AvatarKage commented on scripts/translate.js
> +})
Remove pirate!

2023-09-18 23:51 UTC, ScuffedItalian commented
I will remove those and update stuff per requested. One issue, for Suisse, their national animal isn't an emoji and CH is switzerland's region code. I have no clue what to put for Switzerland, and Deutschland's (Germany's) national animal is also an eagel so it is a little difficult to come up with a complete different one for Deutschland other than DE.

2023-09-19 00:41 UTC, AvatarKage commented
> I will remove those and update stuff per requested. One issue, for Suisse, their national animal isn't an emoji and CH is switzerland's region code. I have no clue what to put for Switzerland, and Deutschland's (Germany's) national animal is also an eagel so it is a little difficult to come up with a complete different one for Deutschland other than DE.

That's fine then. I can find an emoji for it don't! Just leave them blank then, thank you!

2023-09-19 02:03 UTC, im-a-dweeb commented
Alright, all of that has been done. Anything else you'd like me to change?

2023-09-19 03:40 UTC, AvatarKage approved these changes
Thank you!

2023-09-19 03:40 UTC, merged